### ISSUE TITLE
help pis

### ISSUE THREAD

**Issue by HACKED210** [AlipBot/Api-Alpis#28]
throw new Error('site_key is required');
            ^

Error: site_key is required
    at new RecaptchaV2 (/storage/emulated/0/amaster/node_modules/express-recaptcha/dist/v2.js:23:19)
    at Object.<anonymous> (/storage/emulated/0/amaster/routes/auth.js:19:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/storage/emulated/0/amaster/routes/main.js:22:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

**Comment by ahlulmukh** [comment]
ambil keynya digoogle capcha
